### ISSUE TITLE
Change naming scheme of projected_efields to something general

### ISSUE THREAD

**Issue by jackhamel16** [cglosser/QuEST#23]
https://github.com/cglosser/QuEST/blob/4cdfb661128e0d5bef43064a5928d30287edda8b/src/integrator.cpp#L171-L185

**Comment by cglosser** [comment]
Some of the lingo in the integrator is really, really domain specific to the Bloch problem (see link). From a modularity/readability stand point, it's probably best to decouple these some.

**Comment by jackhamel16** [comment]
Are you saying in addition to the naming scheme in evaluator? Also, the only link I see is the one I posted originally.  Are you just referring to that one?

**Comment by cglosser** [comment]
Closed in 598eb02cf8
